// Code generated by Fern. DO NOT EDIT.

package client

import (
	agentmanagement "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/agentmanagement"
	agents "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/agents"
	core "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/core"
	internal "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/internal"
	option "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/option"
	phonenumbers "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/phonenumbers"
	telephony "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/telephony"
)

type Client struct {
	Agents          *agents.Client
	AgentManagement *agentmanagement.Client
	Telephony       *telephony.Client
	PhoneNumbers    *phonenumbers.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Agents:          agents.NewClient(options),
		AgentManagement: agentmanagement.NewClient(options),
		Telephony:       telephony.NewClient(options),
		PhoneNumbers:    phonenumbers.NewClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
