// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/AgoraIO/agora-agents-go/v2/internal"
	big "math/big"
)

var (
	agentThinkAgentManagementRequestFieldAppid             = big.NewInt(1 << 0)
	agentThinkAgentManagementRequestFieldAgentID           = big.NewInt(1 << 1)
	agentThinkAgentManagementRequestFieldText              = big.NewInt(1 << 2)
	agentThinkAgentManagementRequestFieldOnListeningAction = big.NewInt(1 << 3)
	agentThinkAgentManagementRequestFieldOnThinkingAction  = big.NewInt(1 << 4)
	agentThinkAgentManagementRequestFieldOnSpeakingAction  = big.NewInt(1 << 5)
	agentThinkAgentManagementRequestFieldInterruptable     = big.NewInt(1 << 6)
	agentThinkAgentManagementRequestFieldMetadata          = big.NewInt(1 << 7)
)

type AgentThinkAgentManagementRequest struct {
	// The App ID of the project.
	Appid string `json:"-" url:"-"`
	// The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
	AgentID string `json:"-" url:"-"`
	// The custom instruction text to inject into the current conversation pipeline. The system processes this as user input.
	Text string `json:"text" url:"-"`
	// The action to take when the agent is in a listening state:
	// - `inject`: Inject the custom text instruction into the current turn without interrupting it.
	// - `interrupt`: Immediately interrupt the current flow and initiate a new round of dialogue.
	// - `ignore`: Ignore the request.
	OnListeningAction *AgentThinkAgentManagementRequestOnListeningAction `json:"on_listening_action,omitempty" url:"-"`
	// The action to take when the agent is in a thinking state:
	// - `interrupt`: Interrupt the current state and start a new conversation turn.
	// - `ignore`: Ignore the request.
	OnThinkingAction *AgentThinkAgentManagementRequestOnThinkingAction `json:"on_thinking_action,omitempty" url:"-"`
	// The action to take when the agent is in a speaking state:
	// - `interrupt`: Interrupt the current state and start a new conversation turn.
	// - `ignore`: Ignore the request.
	OnSpeakingAction *AgentThinkAgentManagementRequestOnSpeakingAction `json:"on_speaking_action,omitempty" url:"-"`
	// Whether user speech can interrupt the injected instruction:
	// - `true`: User speech can interrupt the instruction.
	// - `false`: User speech cannot interrupt the instruction.
	Interruptable *bool `json:"interruptable,omitempty" url:"-"`
	// Custom metadata in key-value pair format. Use this field to pass additional business information such as identifiers or model references.
	Metadata map[string]string `json:"metadata,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AgentThinkAgentManagementRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAppid sets the Appid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementRequest) SetAppid(appid string) {
	a.Appid = appid
	a.require(agentThinkAgentManagementRequestFieldAppid)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementRequest) SetAgentID(agentID string) {
	a.AgentID = agentID
	a.require(agentThinkAgentManagementRequestFieldAgentID)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementRequest) SetText(text string) {
	a.Text = text
	a.require(agentThinkAgentManagementRequestFieldText)
}

// SetOnListeningAction sets the OnListeningAction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementRequest) SetOnListeningAction(onListeningAction *AgentThinkAgentManagementRequestOnListeningAction) {
	a.OnListeningAction = onListeningAction
	a.require(agentThinkAgentManagementRequestFieldOnListeningAction)
}

// SetOnThinkingAction sets the OnThinkingAction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementRequest) SetOnThinkingAction(onThinkingAction *AgentThinkAgentManagementRequestOnThinkingAction) {
	a.OnThinkingAction = onThinkingAction
	a.require(agentThinkAgentManagementRequestFieldOnThinkingAction)
}

// SetOnSpeakingAction sets the OnSpeakingAction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementRequest) SetOnSpeakingAction(onSpeakingAction *AgentThinkAgentManagementRequestOnSpeakingAction) {
	a.OnSpeakingAction = onSpeakingAction
	a.require(agentThinkAgentManagementRequestFieldOnSpeakingAction)
}

// SetInterruptable sets the Interruptable field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementRequest) SetInterruptable(interruptable *bool) {
	a.Interruptable = interruptable
	a.require(agentThinkAgentManagementRequestFieldInterruptable)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementRequest) SetMetadata(metadata map[string]string) {
	a.Metadata = metadata
	a.require(agentThinkAgentManagementRequestFieldMetadata)
}

// The action to take when the agent is in a listening state:
// - `inject`: Inject the custom text instruction into the current turn without interrupting it.
// - `interrupt`: Immediately interrupt the current flow and initiate a new round of dialogue.
// - `ignore`: Ignore the request.
type AgentThinkAgentManagementRequestOnListeningAction string

const (
	AgentThinkAgentManagementRequestOnListeningActionInject    AgentThinkAgentManagementRequestOnListeningAction = "inject"
	AgentThinkAgentManagementRequestOnListeningActionInterrupt AgentThinkAgentManagementRequestOnListeningAction = "interrupt"
	AgentThinkAgentManagementRequestOnListeningActionIgnore    AgentThinkAgentManagementRequestOnListeningAction = "ignore"
)

func NewAgentThinkAgentManagementRequestOnListeningActionFromString(s string) (AgentThinkAgentManagementRequestOnListeningAction, error) {
	switch s {
	case "inject":
		return AgentThinkAgentManagementRequestOnListeningActionInject, nil
	case "interrupt":
		return AgentThinkAgentManagementRequestOnListeningActionInterrupt, nil
	case "ignore":
		return AgentThinkAgentManagementRequestOnListeningActionIgnore, nil
	}
	var t AgentThinkAgentManagementRequestOnListeningAction
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentThinkAgentManagementRequestOnListeningAction) Ptr() *AgentThinkAgentManagementRequestOnListeningAction {
	return &a
}

// The action to take when the agent is in a speaking state:
// - `interrupt`: Interrupt the current state and start a new conversation turn.
// - `ignore`: Ignore the request.
type AgentThinkAgentManagementRequestOnSpeakingAction string

const (
	AgentThinkAgentManagementRequestOnSpeakingActionInterrupt AgentThinkAgentManagementRequestOnSpeakingAction = "interrupt"
	AgentThinkAgentManagementRequestOnSpeakingActionIgnore    AgentThinkAgentManagementRequestOnSpeakingAction = "ignore"
)

func NewAgentThinkAgentManagementRequestOnSpeakingActionFromString(s string) (AgentThinkAgentManagementRequestOnSpeakingAction, error) {
	switch s {
	case "interrupt":
		return AgentThinkAgentManagementRequestOnSpeakingActionInterrupt, nil
	case "ignore":
		return AgentThinkAgentManagementRequestOnSpeakingActionIgnore, nil
	}
	var t AgentThinkAgentManagementRequestOnSpeakingAction
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentThinkAgentManagementRequestOnSpeakingAction) Ptr() *AgentThinkAgentManagementRequestOnSpeakingAction {
	return &a
}

// The action to take when the agent is in a thinking state:
// - `interrupt`: Interrupt the current state and start a new conversation turn.
// - `ignore`: Ignore the request.
type AgentThinkAgentManagementRequestOnThinkingAction string

const (
	AgentThinkAgentManagementRequestOnThinkingActionInterrupt AgentThinkAgentManagementRequestOnThinkingAction = "interrupt"
	AgentThinkAgentManagementRequestOnThinkingActionIgnore    AgentThinkAgentManagementRequestOnThinkingAction = "ignore"
)

func NewAgentThinkAgentManagementRequestOnThinkingActionFromString(s string) (AgentThinkAgentManagementRequestOnThinkingAction, error) {
	switch s {
	case "interrupt":
		return AgentThinkAgentManagementRequestOnThinkingActionInterrupt, nil
	case "ignore":
		return AgentThinkAgentManagementRequestOnThinkingActionIgnore, nil
	}
	var t AgentThinkAgentManagementRequestOnThinkingAction
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentThinkAgentManagementRequestOnThinkingAction) Ptr() *AgentThinkAgentManagementRequestOnThinkingAction {
	return &a
}

var (
	agentThinkAgentManagementResponseFieldAgentID = big.NewInt(1 << 0)
	agentThinkAgentManagementResponseFieldChannel = big.NewInt(1 << 1)
	agentThinkAgentManagementResponseFieldStartTs = big.NewInt(1 << 2)
)

type AgentThinkAgentManagementResponse struct {
	// Unique identifier of the agent instance.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	// The name of the RTC channel where the agent is located.
	Channel *string `json:"channel,omitempty" url:"channel,omitempty"`
	// Unix timestamp in seconds when the think request was processed.
	StartTs *int `json:"start_ts,omitempty" url:"start_ts,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentThinkAgentManagementResponse) GetAgentID() *string {
	if a == nil {
		return nil
	}
	return a.AgentID
}

func (a *AgentThinkAgentManagementResponse) GetChannel() *string {
	if a == nil {
		return nil
	}
	return a.Channel
}

func (a *AgentThinkAgentManagementResponse) GetStartTs() *int {
	if a == nil {
		return nil
	}
	return a.StartTs
}

func (a *AgentThinkAgentManagementResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentThinkAgentManagementResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementResponse) SetAgentID(agentID *string) {
	a.AgentID = agentID
	a.require(agentThinkAgentManagementResponseFieldAgentID)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementResponse) SetChannel(channel *string) {
	a.Channel = channel
	a.require(agentThinkAgentManagementResponseFieldChannel)
}

// SetStartTs sets the StartTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentThinkAgentManagementResponse) SetStartTs(startTs *int) {
	a.StartTs = startTs
	a.require(agentThinkAgentManagementResponseFieldStartTs)
}

func (a *AgentThinkAgentManagementResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentThinkAgentManagementResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentThinkAgentManagementResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentThinkAgentManagementResponse) MarshalJSON() ([]byte, error) {
	type embed AgentThinkAgentManagementResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentThinkAgentManagementResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}
