// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/AgoraIO/agora-agents-go/v2/internal"
	big "math/big"
)

var (
	addPhoneNumbersRequestFieldProvider       = big.NewInt(1 << 0)
	addPhoneNumbersRequestFieldPhoneNumber    = big.NewInt(1 << 1)
	addPhoneNumbersRequestFieldLabel          = big.NewInt(1 << 2)
	addPhoneNumbersRequestFieldInbound        = big.NewInt(1 << 3)
	addPhoneNumbersRequestFieldOutbound       = big.NewInt(1 << 4)
	addPhoneNumbersRequestFieldInboundConfig  = big.NewInt(1 << 5)
	addPhoneNumbersRequestFieldOutboundConfig = big.NewInt(1 << 6)
)

type AddPhoneNumbersRequest struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider AddPhoneNumbersRequestProvider `json:"provider" url:"-"`
	// Telephone number in E.164 format.
	PhoneNumber string `json:"phone_number" url:"-"`
	// A label used to identify the number.
	Label string `json:"label" url:"-"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"-"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"-"`
	// SIP inbound call configuration.
	InboundConfig *AddPhoneNumbersRequestInboundConfig `json:"inbound_config,omitempty" url:"-"`
	// SIP outbound call configuration.
	OutboundConfig *AddPhoneNumbersRequestOutboundConfig `json:"outbound_config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddPhoneNumbersRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequest) SetProvider(provider AddPhoneNumbersRequestProvider) {
	a.Provider = provider
	a.require(addPhoneNumbersRequestFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequest) SetPhoneNumber(phoneNumber string) {
	a.PhoneNumber = phoneNumber
	a.require(addPhoneNumbersRequestFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequest) SetLabel(label string) {
	a.Label = label
	a.require(addPhoneNumbersRequestFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequest) SetInbound(inbound *bool) {
	a.Inbound = inbound
	a.require(addPhoneNumbersRequestFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequest) SetOutbound(outbound *bool) {
	a.Outbound = outbound
	a.require(addPhoneNumbersRequestFieldOutbound)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequest) SetInboundConfig(inboundConfig *AddPhoneNumbersRequestInboundConfig) {
	a.InboundConfig = inboundConfig
	a.require(addPhoneNumbersRequestFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequest) SetOutboundConfig(outboundConfig *AddPhoneNumbersRequestOutboundConfig) {
	a.OutboundConfig = outboundConfig
	a.require(addPhoneNumbersRequestFieldOutboundConfig)
}

var (
	deletePhoneNumbersRequestFieldPhoneNumber = big.NewInt(1 << 0)
)

type DeletePhoneNumbersRequest struct {
	// Telephone number in E.164 format. For example, +11234567890.
	PhoneNumber string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeletePhoneNumbersRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeletePhoneNumbersRequest) SetPhoneNumber(phoneNumber string) {
	d.PhoneNumber = phoneNumber
	d.require(deletePhoneNumbersRequestFieldPhoneNumber)
}

var (
	getPhoneNumbersRequestFieldPhoneNumber = big.NewInt(1 << 0)
)

type GetPhoneNumbersRequest struct {
	// Telephone number in E.164 format. For example, +11234567890.
	PhoneNumber string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPhoneNumbersRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersRequest) SetPhoneNumber(phoneNumber string) {
	g.PhoneNumber = phoneNumber
	g.require(getPhoneNumbersRequestFieldPhoneNumber)
}

// SIP inbound call configuration.
var (
	addPhoneNumbersRequestInboundConfigFieldAllowedAddresses = big.NewInt(1 << 0)
)

type AddPhoneNumbersRequestInboundConfig struct {
	// List of allowed IP addresses. For example `112.126.15.64/27`
	AllowedAddresses []string `json:"allowed_addresses,omitempty" url:"allowed_addresses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddPhoneNumbersRequestInboundConfig) GetAllowedAddresses() []string {
	if a == nil {
		return nil
	}
	return a.AllowedAddresses
}

func (a *AddPhoneNumbersRequestInboundConfig) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddPhoneNumbersRequestInboundConfig) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAllowedAddresses sets the AllowedAddresses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequestInboundConfig) SetAllowedAddresses(allowedAddresses []string) {
	a.AllowedAddresses = allowedAddresses
	a.require(addPhoneNumbersRequestInboundConfigFieldAllowedAddresses)
}

func (a *AddPhoneNumbersRequestInboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler AddPhoneNumbersRequestInboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddPhoneNumbersRequestInboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddPhoneNumbersRequestInboundConfig) MarshalJSON() ([]byte, error) {
	type embed AddPhoneNumbersRequestInboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddPhoneNumbersRequestInboundConfig) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// SIP outbound call configuration.
var (
	addPhoneNumbersRequestOutboundConfigFieldAddress   = big.NewInt(1 << 0)
	addPhoneNumbersRequestOutboundConfigFieldTransport = big.NewInt(1 << 1)
	addPhoneNumbersRequestOutboundConfigFieldPrefix    = big.NewInt(1 << 2)
)

type AddPhoneNumbersRequestOutboundConfig struct {
	// SIP address. For example `xxx:xxx@sip.example.com`
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Transport protocol. For example `tls`
	Transport *string `json:"transport,omitempty" url:"transport,omitempty"`
	// Number prefix. For example `6036`
	Prefix *string `json:"prefix,omitempty" url:"prefix,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddPhoneNumbersRequestOutboundConfig) GetAddress() *string {
	if a == nil {
		return nil
	}
	return a.Address
}

func (a *AddPhoneNumbersRequestOutboundConfig) GetTransport() *string {
	if a == nil {
		return nil
	}
	return a.Transport
}

func (a *AddPhoneNumbersRequestOutboundConfig) GetPrefix() *string {
	if a == nil {
		return nil
	}
	return a.Prefix
}

func (a *AddPhoneNumbersRequestOutboundConfig) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddPhoneNumbersRequestOutboundConfig) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequestOutboundConfig) SetAddress(address *string) {
	a.Address = address
	a.require(addPhoneNumbersRequestOutboundConfigFieldAddress)
}

// SetTransport sets the Transport field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequestOutboundConfig) SetTransport(transport *string) {
	a.Transport = transport
	a.require(addPhoneNumbersRequestOutboundConfigFieldTransport)
}

// SetPrefix sets the Prefix field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersRequestOutboundConfig) SetPrefix(prefix *string) {
	a.Prefix = prefix
	a.require(addPhoneNumbersRequestOutboundConfigFieldPrefix)
}

func (a *AddPhoneNumbersRequestOutboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler AddPhoneNumbersRequestOutboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddPhoneNumbersRequestOutboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddPhoneNumbersRequestOutboundConfig) MarshalJSON() ([]byte, error) {
	type embed AddPhoneNumbersRequestOutboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddPhoneNumbersRequestOutboundConfig) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type AddPhoneNumbersRequestProvider string

const (
	AddPhoneNumbersRequestProviderByo    AddPhoneNumbersRequestProvider = "byo"
	AddPhoneNumbersRequestProviderTwilio AddPhoneNumbersRequestProvider = "twilio"
)

func NewAddPhoneNumbersRequestProviderFromString(s string) (AddPhoneNumbersRequestProvider, error) {
	switch s {
	case "byo":
		return AddPhoneNumbersRequestProviderByo, nil
	case "twilio":
		return AddPhoneNumbersRequestProviderTwilio, nil
	}
	var t AddPhoneNumbersRequestProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AddPhoneNumbersRequestProvider) Ptr() *AddPhoneNumbersRequestProvider {
	return &a
}

var (
	addPhoneNumbersResponseFieldPhoneNumber        = big.NewInt(1 << 0)
	addPhoneNumbersResponseFieldLabel              = big.NewInt(1 << 1)
	addPhoneNumbersResponseFieldProvider           = big.NewInt(1 << 2)
	addPhoneNumbersResponseFieldInbound            = big.NewInt(1 << 3)
	addPhoneNumbersResponseFieldOutbound           = big.NewInt(1 << 4)
	addPhoneNumbersResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
)

type AddPhoneNumbersResponse struct {
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Number provider.
	Provider *string `json:"provider,omitempty" url:"provider,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *AddPhoneNumbersResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddPhoneNumbersResponse) GetPhoneNumber() *string {
	if a == nil {
		return nil
	}
	return a.PhoneNumber
}

func (a *AddPhoneNumbersResponse) GetLabel() *string {
	if a == nil {
		return nil
	}
	return a.Label
}

func (a *AddPhoneNumbersResponse) GetProvider() *string {
	if a == nil {
		return nil
	}
	return a.Provider
}

func (a *AddPhoneNumbersResponse) GetInbound() *bool {
	if a == nil {
		return nil
	}
	return a.Inbound
}

func (a *AddPhoneNumbersResponse) GetOutbound() *bool {
	if a == nil {
		return nil
	}
	return a.Outbound
}

func (a *AddPhoneNumbersResponse) GetAssociatedPipeline() *AddPhoneNumbersResponseAssociatedPipeline {
	if a == nil {
		return nil
	}
	return a.AssociatedPipeline
}

func (a *AddPhoneNumbersResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddPhoneNumbersResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersResponse) SetPhoneNumber(phoneNumber *string) {
	a.PhoneNumber = phoneNumber
	a.require(addPhoneNumbersResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersResponse) SetLabel(label *string) {
	a.Label = label
	a.require(addPhoneNumbersResponseFieldLabel)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersResponse) SetProvider(provider *string) {
	a.Provider = provider
	a.require(addPhoneNumbersResponseFieldProvider)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersResponse) SetInbound(inbound *bool) {
	a.Inbound = inbound
	a.require(addPhoneNumbersResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersResponse) SetOutbound(outbound *bool) {
	a.Outbound = outbound
	a.require(addPhoneNumbersResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersResponse) SetAssociatedPipeline(associatedPipeline *AddPhoneNumbersResponseAssociatedPipeline) {
	a.AssociatedPipeline = associatedPipeline
	a.require(addPhoneNumbersResponseFieldAssociatedPipeline)
}

func (a *AddPhoneNumbersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AddPhoneNumbersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddPhoneNumbersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddPhoneNumbersResponse) MarshalJSON() ([]byte, error) {
	type embed AddPhoneNumbersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddPhoneNumbersResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	addPhoneNumbersResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	addPhoneNumbersResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type AddPhoneNumbersResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddPhoneNumbersResponseAssociatedPipeline) GetPipelineID() *string {
	if a == nil {
		return nil
	}
	return a.PipelineID
}

func (a *AddPhoneNumbersResponseAssociatedPipeline) GetPipelineName() *string {
	if a == nil {
		return nil
	}
	return a.PipelineName
}

func (a *AddPhoneNumbersResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddPhoneNumbersResponseAssociatedPipeline) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	a.PipelineID = pipelineID
	a.require(addPhoneNumbersResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddPhoneNumbersResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	a.PipelineName = pipelineName
	a.require(addPhoneNumbersResponseAssociatedPipelineFieldPipelineName)
}

func (a *AddPhoneNumbersResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler AddPhoneNumbersResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddPhoneNumbersResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddPhoneNumbersResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed AddPhoneNumbersResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AddPhoneNumbersResponseAssociatedPipeline) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	getPhoneNumbersResponseFieldProvider           = big.NewInt(1 << 0)
	getPhoneNumbersResponseFieldPhoneNumber        = big.NewInt(1 << 1)
	getPhoneNumbersResponseFieldLabel              = big.NewInt(1 << 2)
	getPhoneNumbersResponseFieldInbound            = big.NewInt(1 << 3)
	getPhoneNumbersResponseFieldOutbound           = big.NewInt(1 << 4)
	getPhoneNumbersResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
	getPhoneNumbersResponseFieldInboundConfig      = big.NewInt(1 << 6)
	getPhoneNumbersResponseFieldOutboundConfig     = big.NewInt(1 << 7)
)

type GetPhoneNumbersResponse struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider *GetPhoneNumbersResponseProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *GetPhoneNumbersResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPhoneNumbersResponse) GetProvider() *GetPhoneNumbersResponseProvider {
	if g == nil {
		return nil
	}
	return g.Provider
}

func (g *GetPhoneNumbersResponse) GetPhoneNumber() *string {
	if g == nil {
		return nil
	}
	return g.PhoneNumber
}

func (g *GetPhoneNumbersResponse) GetLabel() *string {
	if g == nil {
		return nil
	}
	return g.Label
}

func (g *GetPhoneNumbersResponse) GetInbound() *bool {
	if g == nil {
		return nil
	}
	return g.Inbound
}

func (g *GetPhoneNumbersResponse) GetOutbound() *bool {
	if g == nil {
		return nil
	}
	return g.Outbound
}

func (g *GetPhoneNumbersResponse) GetAssociatedPipeline() *GetPhoneNumbersResponseAssociatedPipeline {
	if g == nil {
		return nil
	}
	return g.AssociatedPipeline
}

func (g *GetPhoneNumbersResponse) GetInboundConfig() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.InboundConfig
}

func (g *GetPhoneNumbersResponse) GetOutboundConfig() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.OutboundConfig
}

func (g *GetPhoneNumbersResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPhoneNumbersResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponse) SetProvider(provider *GetPhoneNumbersResponseProvider) {
	g.Provider = provider
	g.require(getPhoneNumbersResponseFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponse) SetPhoneNumber(phoneNumber *string) {
	g.PhoneNumber = phoneNumber
	g.require(getPhoneNumbersResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponse) SetLabel(label *string) {
	g.Label = label
	g.require(getPhoneNumbersResponseFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponse) SetInbound(inbound *bool) {
	g.Inbound = inbound
	g.require(getPhoneNumbersResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponse) SetOutbound(outbound *bool) {
	g.Outbound = outbound
	g.require(getPhoneNumbersResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponse) SetAssociatedPipeline(associatedPipeline *GetPhoneNumbersResponseAssociatedPipeline) {
	g.AssociatedPipeline = associatedPipeline
	g.require(getPhoneNumbersResponseFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponse) SetInboundConfig(inboundConfig map[string]interface{}) {
	g.InboundConfig = inboundConfig
	g.require(getPhoneNumbersResponseFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponse) SetOutboundConfig(outboundConfig map[string]interface{}) {
	g.OutboundConfig = outboundConfig
	g.require(getPhoneNumbersResponseFieldOutboundConfig)
}

func (g *GetPhoneNumbersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPhoneNumbersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPhoneNumbersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPhoneNumbersResponse) MarshalJSON() ([]byte, error) {
	type embed GetPhoneNumbersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPhoneNumbersResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	getPhoneNumbersResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	getPhoneNumbersResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type GetPhoneNumbersResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetPhoneNumbersResponseAssociatedPipeline) GetPipelineID() *string {
	if g == nil {
		return nil
	}
	return g.PipelineID
}

func (g *GetPhoneNumbersResponseAssociatedPipeline) GetPipelineName() *string {
	if g == nil {
		return nil
	}
	return g.PipelineName
}

func (g *GetPhoneNumbersResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetPhoneNumbersResponseAssociatedPipeline) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	g.PipelineID = pipelineID
	g.require(getPhoneNumbersResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPhoneNumbersResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	g.PipelineName = pipelineName
	g.require(getPhoneNumbersResponseAssociatedPipelineFieldPipelineName)
}

func (g *GetPhoneNumbersResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler GetPhoneNumbersResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetPhoneNumbersResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetPhoneNumbersResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed GetPhoneNumbersResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetPhoneNumbersResponseAssociatedPipeline) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type GetPhoneNumbersResponseProvider string

const (
	GetPhoneNumbersResponseProviderByo    GetPhoneNumbersResponseProvider = "byo"
	GetPhoneNumbersResponseProviderTwilio GetPhoneNumbersResponseProvider = "twilio"
)

func NewGetPhoneNumbersResponseProviderFromString(s string) (GetPhoneNumbersResponseProvider, error) {
	switch s {
	case "byo":
		return GetPhoneNumbersResponseProviderByo, nil
	case "twilio":
		return GetPhoneNumbersResponseProviderTwilio, nil
	}
	var t GetPhoneNumbersResponseProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetPhoneNumbersResponseProvider) Ptr() *GetPhoneNumbersResponseProvider {
	return &g
}

var (
	listPhoneNumbersResponseItemFieldProvider           = big.NewInt(1 << 0)
	listPhoneNumbersResponseItemFieldPhoneNumber        = big.NewInt(1 << 1)
	listPhoneNumbersResponseItemFieldLabel              = big.NewInt(1 << 2)
	listPhoneNumbersResponseItemFieldInbound            = big.NewInt(1 << 3)
	listPhoneNumbersResponseItemFieldOutbound           = big.NewInt(1 << 4)
	listPhoneNumbersResponseItemFieldAssociatedPipeline = big.NewInt(1 << 5)
	listPhoneNumbersResponseItemFieldInboundConfig      = big.NewInt(1 << 6)
	listPhoneNumbersResponseItemFieldOutboundConfig     = big.NewInt(1 << 7)
)

type ListPhoneNumbersResponseItem struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own).
	// - `twilio`: Twilio.
	Provider *ListPhoneNumbersResponseItemProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *ListPhoneNumbersResponseItemAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPhoneNumbersResponseItem) GetProvider() *ListPhoneNumbersResponseItemProvider {
	if l == nil {
		return nil
	}
	return l.Provider
}

func (l *ListPhoneNumbersResponseItem) GetPhoneNumber() *string {
	if l == nil {
		return nil
	}
	return l.PhoneNumber
}

func (l *ListPhoneNumbersResponseItem) GetLabel() *string {
	if l == nil {
		return nil
	}
	return l.Label
}

func (l *ListPhoneNumbersResponseItem) GetInbound() *bool {
	if l == nil {
		return nil
	}
	return l.Inbound
}

func (l *ListPhoneNumbersResponseItem) GetOutbound() *bool {
	if l == nil {
		return nil
	}
	return l.Outbound
}

func (l *ListPhoneNumbersResponseItem) GetAssociatedPipeline() *ListPhoneNumbersResponseItemAssociatedPipeline {
	if l == nil {
		return nil
	}
	return l.AssociatedPipeline
}

func (l *ListPhoneNumbersResponseItem) GetInboundConfig() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.InboundConfig
}

func (l *ListPhoneNumbersResponseItem) GetOutboundConfig() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.OutboundConfig
}

func (l *ListPhoneNumbersResponseItem) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListPhoneNumbersResponseItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItem) SetProvider(provider *ListPhoneNumbersResponseItemProvider) {
	l.Provider = provider
	l.require(listPhoneNumbersResponseItemFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItem) SetPhoneNumber(phoneNumber *string) {
	l.PhoneNumber = phoneNumber
	l.require(listPhoneNumbersResponseItemFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItem) SetLabel(label *string) {
	l.Label = label
	l.require(listPhoneNumbersResponseItemFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItem) SetInbound(inbound *bool) {
	l.Inbound = inbound
	l.require(listPhoneNumbersResponseItemFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItem) SetOutbound(outbound *bool) {
	l.Outbound = outbound
	l.require(listPhoneNumbersResponseItemFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItem) SetAssociatedPipeline(associatedPipeline *ListPhoneNumbersResponseItemAssociatedPipeline) {
	l.AssociatedPipeline = associatedPipeline
	l.require(listPhoneNumbersResponseItemFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItem) SetInboundConfig(inboundConfig map[string]interface{}) {
	l.InboundConfig = inboundConfig
	l.require(listPhoneNumbersResponseItemFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItem) SetOutboundConfig(outboundConfig map[string]interface{}) {
	l.OutboundConfig = outboundConfig
	l.require(listPhoneNumbersResponseItemFieldOutboundConfig)
}

func (l *ListPhoneNumbersResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPhoneNumbersResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPhoneNumbersResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPhoneNumbersResponseItem) MarshalJSON() ([]byte, error) {
	type embed ListPhoneNumbersResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPhoneNumbersResponseItem) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	listPhoneNumbersResponseItemAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	listPhoneNumbersResponseItemAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type ListPhoneNumbersResponseItemAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListPhoneNumbersResponseItemAssociatedPipeline) GetPipelineID() *string {
	if l == nil {
		return nil
	}
	return l.PipelineID
}

func (l *ListPhoneNumbersResponseItemAssociatedPipeline) GetPipelineName() *string {
	if l == nil {
		return nil
	}
	return l.PipelineName
}

func (l *ListPhoneNumbersResponseItemAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListPhoneNumbersResponseItemAssociatedPipeline) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItemAssociatedPipeline) SetPipelineID(pipelineID *string) {
	l.PipelineID = pipelineID
	l.require(listPhoneNumbersResponseItemAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPhoneNumbersResponseItemAssociatedPipeline) SetPipelineName(pipelineName *string) {
	l.PipelineName = pipelineName
	l.require(listPhoneNumbersResponseItemAssociatedPipelineFieldPipelineName)
}

func (l *ListPhoneNumbersResponseItemAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler ListPhoneNumbersResponseItemAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListPhoneNumbersResponseItemAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListPhoneNumbersResponseItemAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed ListPhoneNumbersResponseItemAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListPhoneNumbersResponseItemAssociatedPipeline) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Number provider:
// - `byo`: BYO (Bring Your Own).
// - `twilio`: Twilio.
type ListPhoneNumbersResponseItemProvider string

const (
	ListPhoneNumbersResponseItemProviderByo    ListPhoneNumbersResponseItemProvider = "byo"
	ListPhoneNumbersResponseItemProviderTwilio ListPhoneNumbersResponseItemProvider = "twilio"
)

func NewListPhoneNumbersResponseItemProviderFromString(s string) (ListPhoneNumbersResponseItemProvider, error) {
	switch s {
	case "byo":
		return ListPhoneNumbersResponseItemProviderByo, nil
	case "twilio":
		return ListPhoneNumbersResponseItemProviderTwilio, nil
	}
	var t ListPhoneNumbersResponseItemProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListPhoneNumbersResponseItemProvider) Ptr() *ListPhoneNumbersResponseItemProvider {
	return &l
}

// Update inbound call configuration. Passing `null` will clear the configuration.
var (
	updatePhoneNumbersRequestInboundConfigFieldPipelineID = big.NewInt(1 << 0)
)

type UpdatePhoneNumbersRequestInboundConfig struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePhoneNumbersRequestInboundConfig) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdatePhoneNumbersRequestInboundConfig) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePhoneNumbersRequestInboundConfig) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersRequestInboundConfig) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updatePhoneNumbersRequestInboundConfigFieldPipelineID)
}

func (u *UpdatePhoneNumbersRequestInboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePhoneNumbersRequestInboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePhoneNumbersRequestInboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePhoneNumbersRequestInboundConfig) MarshalJSON() ([]byte, error) {
	type embed UpdatePhoneNumbersRequestInboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePhoneNumbersRequestInboundConfig) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Update outbound call configuration. Passing `null` will clear the configuration.
var (
	updatePhoneNumbersRequestOutboundConfigFieldPipelineID = big.NewInt(1 << 0)
)

type UpdatePhoneNumbersRequestOutboundConfig struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePhoneNumbersRequestOutboundConfig) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdatePhoneNumbersRequestOutboundConfig) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePhoneNumbersRequestOutboundConfig) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersRequestOutboundConfig) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updatePhoneNumbersRequestOutboundConfigFieldPipelineID)
}

func (u *UpdatePhoneNumbersRequestOutboundConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePhoneNumbersRequestOutboundConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePhoneNumbersRequestOutboundConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePhoneNumbersRequestOutboundConfig) MarshalJSON() ([]byte, error) {
	type embed UpdatePhoneNumbersRequestOutboundConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePhoneNumbersRequestOutboundConfig) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updatePhoneNumbersResponseFieldProvider           = big.NewInt(1 << 0)
	updatePhoneNumbersResponseFieldPhoneNumber        = big.NewInt(1 << 1)
	updatePhoneNumbersResponseFieldLabel              = big.NewInt(1 << 2)
	updatePhoneNumbersResponseFieldInbound            = big.NewInt(1 << 3)
	updatePhoneNumbersResponseFieldOutbound           = big.NewInt(1 << 4)
	updatePhoneNumbersResponseFieldAssociatedPipeline = big.NewInt(1 << 5)
	updatePhoneNumbersResponseFieldInboundConfig      = big.NewInt(1 << 6)
	updatePhoneNumbersResponseFieldOutboundConfig     = big.NewInt(1 << 7)
)

type UpdatePhoneNumbersResponse struct {
	// Number provider:
	// - `byo`: BYO (Bring Your Own)
	// - `twilio`: Twilio
	Provider *UpdatePhoneNumbersResponseProvider `json:"provider,omitempty" url:"provider,omitempty"`
	// A telephone number in E.164 format, used as a unique identifier.
	PhoneNumber *string `json:"phone_number,omitempty" url:"phone_number,omitempty"`
	// A label used to identify the number.
	Label *string `json:"label,omitempty" url:"label,omitempty"`
	// Whether the number supports inbound calls.
	Inbound *bool `json:"inbound,omitempty" url:"inbound,omitempty"`
	// Whether the number supports outbound calls.
	Outbound *bool `json:"outbound,omitempty" url:"outbound,omitempty"`
	// The associated pipeline information. Returns `null` if no pipeline is associated.
	AssociatedPipeline *UpdatePhoneNumbersResponseAssociatedPipeline `json:"associated_pipeline,omitempty" url:"associated_pipeline,omitempty"`
	// SIP inbound call configuration details. Returns `null` if not configured.
	InboundConfig map[string]interface{} `json:"inbound_config,omitempty" url:"inbound_config,omitempty"`
	// SIP outbound call configuration details. Returns `null` if not configured.
	OutboundConfig map[string]interface{} `json:"outbound_config,omitempty" url:"outbound_config,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePhoneNumbersResponse) GetProvider() *UpdatePhoneNumbersResponseProvider {
	if u == nil {
		return nil
	}
	return u.Provider
}

func (u *UpdatePhoneNumbersResponse) GetPhoneNumber() *string {
	if u == nil {
		return nil
	}
	return u.PhoneNumber
}

func (u *UpdatePhoneNumbersResponse) GetLabel() *string {
	if u == nil {
		return nil
	}
	return u.Label
}

func (u *UpdatePhoneNumbersResponse) GetInbound() *bool {
	if u == nil {
		return nil
	}
	return u.Inbound
}

func (u *UpdatePhoneNumbersResponse) GetOutbound() *bool {
	if u == nil {
		return nil
	}
	return u.Outbound
}

func (u *UpdatePhoneNumbersResponse) GetAssociatedPipeline() *UpdatePhoneNumbersResponseAssociatedPipeline {
	if u == nil {
		return nil
	}
	return u.AssociatedPipeline
}

func (u *UpdatePhoneNumbersResponse) GetInboundConfig() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.InboundConfig
}

func (u *UpdatePhoneNumbersResponse) GetOutboundConfig() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.OutboundConfig
}

func (u *UpdatePhoneNumbersResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePhoneNumbersResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponse) SetProvider(provider *UpdatePhoneNumbersResponseProvider) {
	u.Provider = provider
	u.require(updatePhoneNumbersResponseFieldProvider)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponse) SetPhoneNumber(phoneNumber *string) {
	u.PhoneNumber = phoneNumber
	u.require(updatePhoneNumbersResponseFieldPhoneNumber)
}

// SetLabel sets the Label field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponse) SetLabel(label *string) {
	u.Label = label
	u.require(updatePhoneNumbersResponseFieldLabel)
}

// SetInbound sets the Inbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponse) SetInbound(inbound *bool) {
	u.Inbound = inbound
	u.require(updatePhoneNumbersResponseFieldInbound)
}

// SetOutbound sets the Outbound field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponse) SetOutbound(outbound *bool) {
	u.Outbound = outbound
	u.require(updatePhoneNumbersResponseFieldOutbound)
}

// SetAssociatedPipeline sets the AssociatedPipeline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponse) SetAssociatedPipeline(associatedPipeline *UpdatePhoneNumbersResponseAssociatedPipeline) {
	u.AssociatedPipeline = associatedPipeline
	u.require(updatePhoneNumbersResponseFieldAssociatedPipeline)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponse) SetInboundConfig(inboundConfig map[string]interface{}) {
	u.InboundConfig = inboundConfig
	u.require(updatePhoneNumbersResponseFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponse) SetOutboundConfig(outboundConfig map[string]interface{}) {
	u.OutboundConfig = outboundConfig
	u.require(updatePhoneNumbersResponseFieldOutboundConfig)
}

func (u *UpdatePhoneNumbersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePhoneNumbersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePhoneNumbersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePhoneNumbersResponse) MarshalJSON() ([]byte, error) {
	type embed UpdatePhoneNumbersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePhoneNumbersResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// The associated pipeline information. Returns `null` if no pipeline is associated.
var (
	updatePhoneNumbersResponseAssociatedPipelineFieldPipelineID   = big.NewInt(1 << 0)
	updatePhoneNumbersResponseAssociatedPipelineFieldPipelineName = big.NewInt(1 << 1)
)

type UpdatePhoneNumbersResponseAssociatedPipeline struct {
	// Pipeline ID.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Pipeline name.
	PipelineName *string `json:"pipeline_name,omitempty" url:"pipeline_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePhoneNumbersResponseAssociatedPipeline) GetPipelineID() *string {
	if u == nil {
		return nil
	}
	return u.PipelineID
}

func (u *UpdatePhoneNumbersResponseAssociatedPipeline) GetPipelineName() *string {
	if u == nil {
		return nil
	}
	return u.PipelineName
}

func (u *UpdatePhoneNumbersResponseAssociatedPipeline) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdatePhoneNumbersResponseAssociatedPipeline) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponseAssociatedPipeline) SetPipelineID(pipelineID *string) {
	u.PipelineID = pipelineID
	u.require(updatePhoneNumbersResponseAssociatedPipelineFieldPipelineID)
}

// SetPipelineName sets the PipelineName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersResponseAssociatedPipeline) SetPipelineName(pipelineName *string) {
	u.PipelineName = pipelineName
	u.require(updatePhoneNumbersResponseAssociatedPipelineFieldPipelineName)
}

func (u *UpdatePhoneNumbersResponseAssociatedPipeline) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePhoneNumbersResponseAssociatedPipeline
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePhoneNumbersResponseAssociatedPipeline(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePhoneNumbersResponseAssociatedPipeline) MarshalJSON() ([]byte, error) {
	type embed UpdatePhoneNumbersResponseAssociatedPipeline
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePhoneNumbersResponseAssociatedPipeline) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Number provider:
// - `byo`: BYO (Bring Your Own)
// - `twilio`: Twilio
type UpdatePhoneNumbersResponseProvider string

const (
	UpdatePhoneNumbersResponseProviderByo    UpdatePhoneNumbersResponseProvider = "byo"
	UpdatePhoneNumbersResponseProviderTwilio UpdatePhoneNumbersResponseProvider = "twilio"
)

func NewUpdatePhoneNumbersResponseProviderFromString(s string) (UpdatePhoneNumbersResponseProvider, error) {
	switch s {
	case "byo":
		return UpdatePhoneNumbersResponseProviderByo, nil
	case "twilio":
		return UpdatePhoneNumbersResponseProviderTwilio, nil
	}
	var t UpdatePhoneNumbersResponseProvider
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdatePhoneNumbersResponseProvider) Ptr() *UpdatePhoneNumbersResponseProvider {
	return &u
}

var (
	updatePhoneNumbersRequestFieldPhoneNumber    = big.NewInt(1 << 0)
	updatePhoneNumbersRequestFieldInboundConfig  = big.NewInt(1 << 1)
	updatePhoneNumbersRequestFieldOutboundConfig = big.NewInt(1 << 2)
)

type UpdatePhoneNumbersRequest struct {
	// Telephone number in E.164 format. For example, +11234567890.
	PhoneNumber string `json:"-" url:"-"`
	// Update inbound call configuration. Passing `null` will clear the configuration.
	InboundConfig *UpdatePhoneNumbersRequestInboundConfig `json:"inbound_config,omitempty" url:"-"`
	// Update outbound call configuration. Passing `null` will clear the configuration.
	OutboundConfig *UpdatePhoneNumbersRequestOutboundConfig `json:"outbound_config,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdatePhoneNumbersRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetPhoneNumber sets the PhoneNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersRequest) SetPhoneNumber(phoneNumber string) {
	u.PhoneNumber = phoneNumber
	u.require(updatePhoneNumbersRequestFieldPhoneNumber)
}

// SetInboundConfig sets the InboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersRequest) SetInboundConfig(inboundConfig *UpdatePhoneNumbersRequestInboundConfig) {
	u.InboundConfig = inboundConfig
	u.require(updatePhoneNumbersRequestFieldInboundConfig)
}

// SetOutboundConfig sets the OutboundConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePhoneNumbersRequest) SetOutboundConfig(outboundConfig *UpdatePhoneNumbersRequestOutboundConfig) {
	u.OutboundConfig = outboundConfig
	u.require(updatePhoneNumbersRequestFieldOutboundConfig)
}
