// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/AgoraIO/agora-agents-go/v2/internal"
	big "math/big"
)

var (
	callTelephonyRequestFieldAppid      = big.NewInt(1 << 0)
	callTelephonyRequestFieldName       = big.NewInt(1 << 1)
	callTelephonyRequestFieldSip        = big.NewInt(1 << 2)
	callTelephonyRequestFieldPipelineID = big.NewInt(1 << 3)
	callTelephonyRequestFieldProperties = big.NewInt(1 << 4)
)

type CallTelephonyRequest struct {
	// The App ID of the project.
	Appid string `json:"-" url:"-"`
	// The name identifier of the call session.
	Name string `json:"name" url:"-"`
	// SIP (Session Initiation Protocol) call configuration object.
	Sip *CallTelephonyRequestSip `json:"sip,omitempty" url:"-"`
	// The unique ID of a published project in AI Studio.
	PipelineID *string `json:"pipeline_id,omitempty" url:"-"`
	// Call attribute configuration. The content of this field varies depending on the invocation method:
	// - **Using pipeline ID**: Simply pass in `channel`, `token`, `agent_rtc_uid`, and `remote_rtc_uids`.
	// - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.
	Properties *CallTelephonyRequestProperties `json:"properties,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CallTelephonyRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAppid sets the Appid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequest) SetAppid(appid string) {
	c.Appid = appid
	c.require(callTelephonyRequestFieldAppid)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequest) SetName(name string) {
	c.Name = name
	c.require(callTelephonyRequestFieldName)
}

// SetSip sets the Sip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequest) SetSip(sip *CallTelephonyRequestSip) {
	c.Sip = sip
	c.require(callTelephonyRequestFieldSip)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequest) SetPipelineID(pipelineID *string) {
	c.PipelineID = pipelineID
	c.require(callTelephonyRequestFieldPipelineID)
}

// SetProperties sets the Properties field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequest) SetProperties(properties *CallTelephonyRequestProperties) {
	c.Properties = properties
	c.require(callTelephonyRequestFieldProperties)
}

var (
	getTelephonyRequestFieldAppid   = big.NewInt(1 << 0)
	getTelephonyRequestFieldAgentID = big.NewInt(1 << 1)
)

type GetTelephonyRequest struct {
	// The App ID of the project.
	Appid string `json:"-" url:"-"`
	// The agent ID you obtained after successfully calling the API to initiate an outbound call.
	AgentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTelephonyRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAppid sets the Appid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyRequest) SetAppid(appid string) {
	g.Appid = appid
	g.require(getTelephonyRequestFieldAppid)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyRequest) SetAgentID(agentID string) {
	g.AgentID = agentID
	g.require(getTelephonyRequestFieldAgentID)
}

var (
	hangupTelephonyRequestFieldAppid   = big.NewInt(1 << 0)
	hangupTelephonyRequestFieldAgentID = big.NewInt(1 << 1)
)

type HangupTelephonyRequest struct {
	// The App ID of the project.
	Appid string `json:"-" url:"-"`
	// The agent ID you obtained after successfully calling the API to initiate an outbound call.
	AgentID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (h *HangupTelephonyRequest) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

// SetAppid sets the Appid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HangupTelephonyRequest) SetAppid(appid string) {
	h.Appid = appid
	h.require(hangupTelephonyRequestFieldAppid)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HangupTelephonyRequest) SetAgentID(agentID string) {
	h.AgentID = agentID
	h.require(hangupTelephonyRequestFieldAgentID)
}

var (
	listTelephonyRequestFieldAppid    = big.NewInt(1 << 0)
	listTelephonyRequestFieldNumber   = big.NewInt(1 << 1)
	listTelephonyRequestFieldFromTime = big.NewInt(1 << 2)
	listTelephonyRequestFieldToTime   = big.NewInt(1 << 3)
	listTelephonyRequestFieldType     = big.NewInt(1 << 4)
	listTelephonyRequestFieldLimit    = big.NewInt(1 << 5)
	listTelephonyRequestFieldCursor   = big.NewInt(1 << 6)
)

type ListTelephonyRequest struct {
	// The App ID of the project.
	Appid string `json:"-" url:"-"`
	// Filter by phone number. Can be either the calling number or the called number.
	Number *string `json:"-" url:"number,omitempty"`
	// Query list start timestamp (in seconds). Default is 60 days ago.
	FromTime *int `json:"-" url:"from_time,omitempty"`
	// Query list end timestamp (in seconds). Default is current time.
	ToTime *int `json:"-" url:"to_time,omitempty"`
	// Call type filter:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	//
	// If not specified, all call types are returned.
	Type *ListTelephonyRequestType `json:"-" url:"type,omitempty"`
	// Maximum number of items returned in a single page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Pagination cursor. Use the `agent_id` from the previous page as the cursor for the next page.
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListTelephonyRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAppid sets the Appid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyRequest) SetAppid(appid string) {
	l.Appid = appid
	l.require(listTelephonyRequestFieldAppid)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyRequest) SetNumber(number *string) {
	l.Number = number
	l.require(listTelephonyRequestFieldNumber)
}

// SetFromTime sets the FromTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyRequest) SetFromTime(fromTime *int) {
	l.FromTime = fromTime
	l.require(listTelephonyRequestFieldFromTime)
}

// SetToTime sets the ToTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyRequest) SetToTime(toTime *int) {
	l.ToTime = toTime
	l.require(listTelephonyRequestFieldToTime)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyRequest) SetType(type_ *ListTelephonyRequestType) {
	l.Type = type_
	l.require(listTelephonyRequestFieldType)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listTelephonyRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listTelephonyRequestFieldCursor)
}

// Call attribute configuration. The content of this field varies depending on the invocation method:
// - **Using pipeline ID**: Simply pass in `channel`, `token`, `agent_rtc_uid`, and `remote_rtc_uids`.
// - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.
var (
	callTelephonyRequestPropertiesFieldChannel       = big.NewInt(1 << 0)
	callTelephonyRequestPropertiesFieldToken         = big.NewInt(1 << 1)
	callTelephonyRequestPropertiesFieldAgentRtcUID   = big.NewInt(1 << 2)
	callTelephonyRequestPropertiesFieldRemoteRtcUIDs = big.NewInt(1 << 3)
)

type CallTelephonyRequestProperties struct {
	// RTC channel name.
	Channel string `json:"channel" url:"channel"`
	// RTC Channel Token.
	Token string `json:"token" url:"token"`
	// The agent's user ID in the RTC channel.
	AgentRtcUID string `json:"agent_rtc_uid" url:"agent_rtc_uid"`
	// A list of RTC user IDs. When using pipeline ID, this should contain the SIP gateway UID.
	RemoteRtcUIDs []string `json:"remote_rtc_uids,omitempty" url:"remote_rtc_uids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (c *CallTelephonyRequestProperties) GetChannel() string {
	if c == nil {
		return ""
	}
	return c.Channel
}

func (c *CallTelephonyRequestProperties) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *CallTelephonyRequestProperties) GetAgentRtcUID() string {
	if c == nil {
		return ""
	}
	return c.AgentRtcUID
}

func (c *CallTelephonyRequestProperties) GetRemoteRtcUIDs() []string {
	if c == nil {
		return nil
	}
	return c.RemoteRtcUIDs
}

func (c *CallTelephonyRequestProperties) GetExtraProperties() map[string]interface{} {
	return c.ExtraProperties
}

func (c *CallTelephonyRequestProperties) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequestProperties) SetChannel(channel string) {
	c.Channel = channel
	c.require(callTelephonyRequestPropertiesFieldChannel)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequestProperties) SetToken(token string) {
	c.Token = token
	c.require(callTelephonyRequestPropertiesFieldToken)
}

// SetAgentRtcUID sets the AgentRtcUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequestProperties) SetAgentRtcUID(agentRtcUID string) {
	c.AgentRtcUID = agentRtcUID
	c.require(callTelephonyRequestPropertiesFieldAgentRtcUID)
}

// SetRemoteRtcUIDs sets the RemoteRtcUIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequestProperties) SetRemoteRtcUIDs(remoteRtcUIDs []string) {
	c.RemoteRtcUIDs = remoteRtcUIDs
	c.require(callTelephonyRequestPropertiesFieldRemoteRtcUIDs)
}

func (c *CallTelephonyRequestProperties) UnmarshalJSON(data []byte) error {
	type embed CallTelephonyRequestProperties
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CallTelephonyRequestProperties(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.ExtraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CallTelephonyRequestProperties) MarshalJSON() ([]byte, error) {
	type embed CallTelephonyRequestProperties
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, c.ExtraProperties)
}

func (c *CallTelephonyRequestProperties) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// SIP (Session Initiation Protocol) call configuration object.
var (
	callTelephonyRequestSipFieldToNumber   = big.NewInt(1 << 0)
	callTelephonyRequestSipFieldFromNumber = big.NewInt(1 << 1)
	callTelephonyRequestSipFieldRtcUID     = big.NewInt(1 << 2)
	callTelephonyRequestSipFieldRtcToken   = big.NewInt(1 << 3)
)

type CallTelephonyRequestSip struct {
	// Called number (target phone number), in E.164 format.
	ToNumber string `json:"to_number" url:"to_number"`
	// Caller ID (the number that initiated the call), in E.164 format.
	FromNumber string `json:"from_number" url:"from_number"`
	// The RTC UID used by the SIP gateway.
	RtcUID string `json:"rtc_uid" url:"rtc_uid"`
	// The RTC token used by the SIP gateway.
	RtcToken string `json:"rtc_token" url:"rtc_token"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CallTelephonyRequestSip) GetToNumber() string {
	if c == nil {
		return ""
	}
	return c.ToNumber
}

func (c *CallTelephonyRequestSip) GetFromNumber() string {
	if c == nil {
		return ""
	}
	return c.FromNumber
}

func (c *CallTelephonyRequestSip) GetRtcUID() string {
	if c == nil {
		return ""
	}
	return c.RtcUID
}

func (c *CallTelephonyRequestSip) GetRtcToken() string {
	if c == nil {
		return ""
	}
	return c.RtcToken
}

func (c *CallTelephonyRequestSip) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CallTelephonyRequestSip) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequestSip) SetToNumber(toNumber string) {
	c.ToNumber = toNumber
	c.require(callTelephonyRequestSipFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequestSip) SetFromNumber(fromNumber string) {
	c.FromNumber = fromNumber
	c.require(callTelephonyRequestSipFieldFromNumber)
}

// SetRtcUID sets the RtcUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequestSip) SetRtcUID(rtcUID string) {
	c.RtcUID = rtcUID
	c.require(callTelephonyRequestSipFieldRtcUID)
}

// SetRtcToken sets the RtcToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyRequestSip) SetRtcToken(rtcToken string) {
	c.RtcToken = rtcToken
	c.require(callTelephonyRequestSipFieldRtcToken)
}

func (c *CallTelephonyRequestSip) UnmarshalJSON(data []byte) error {
	type unmarshaler CallTelephonyRequestSip
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CallTelephonyRequestSip(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CallTelephonyRequestSip) MarshalJSON() ([]byte, error) {
	type embed CallTelephonyRequestSip
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CallTelephonyRequestSip) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	callTelephonyResponseFieldAgentID = big.NewInt(1 << 0)
)

type CallTelephonyResponse struct {
	// Unique ID of the agent instance. Use it to query call status, control call flow, and perform other operations.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CallTelephonyResponse) GetAgentID() *string {
	if c == nil {
		return nil
	}
	return c.AgentID
}

func (c *CallTelephonyResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CallTelephonyResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CallTelephonyResponse) SetAgentID(agentID *string) {
	c.AgentID = agentID
	c.require(callTelephonyResponseFieldAgentID)
}

func (c *CallTelephonyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CallTelephonyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CallTelephonyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CallTelephonyResponse) MarshalJSON() ([]byte, error) {
	type embed CallTelephonyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CallTelephonyResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getTelephonyResponseFieldToNumber   = big.NewInt(1 << 0)
	getTelephonyResponseFieldFromNumber = big.NewInt(1 << 1)
	getTelephonyResponseFieldPipelineID = big.NewInt(1 << 2)
	getTelephonyResponseFieldType       = big.NewInt(1 << 3)
	getTelephonyResponseFieldAgentID    = big.NewInt(1 << 4)
	getTelephonyResponseFieldChannel    = big.NewInt(1 << 5)
	getTelephonyResponseFieldReason     = big.NewInt(1 << 6)
	getTelephonyResponseFieldCreateTs   = big.NewInt(1 << 7)
	getTelephonyResponseFieldState      = big.NewInt(1 << 8)
	getTelephonyResponseFieldStopTs     = big.NewInt(1 << 9)
)

type GetTelephonyResponse struct {
	// The number called.
	ToNumber *string `json:"to_number,omitempty" url:"to_number,omitempty"`
	// Caller ID.
	FromNumber *string `json:"from_number,omitempty" url:"from_number,omitempty"`
	// The unique ID of a published project in AI Studio. Can be obtained in AI Studio - Project - Release Management.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Call type:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	Type *GetTelephonyResponseType `json:"type,omitempty" url:"type,omitempty"`
	// A unique identifier for the call session.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	// RTC channel name.
	Channel *string `json:"channel,omitempty" url:"channel,omitempty"`
	// Reason for call ending:
	// - `request`: Actively hung up.
	// - `hangup`: The other party hung up.
	// - `failed`: Call failed.
	Reason *GetTelephonyResponseReason `json:"reason,omitempty" url:"reason,omitempty"`
	// Call creation timestamp (in seconds).
	CreateTs *int `json:"create_ts,omitempty" url:"create_ts,omitempty"`
	// Call status:
	// - `answered`: The call was answered.
	// - `hangup`: The call was disconnected.
	State *GetTelephonyResponseState `json:"state,omitempty" url:"state,omitempty"`
	// Call end timestamp (in seconds). Returns `0` or `null` if the call has not ended.
	StopTs *int `json:"stop_ts,omitempty" url:"stop_ts,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetTelephonyResponse) GetToNumber() *string {
	if g == nil {
		return nil
	}
	return g.ToNumber
}

func (g *GetTelephonyResponse) GetFromNumber() *string {
	if g == nil {
		return nil
	}
	return g.FromNumber
}

func (g *GetTelephonyResponse) GetPipelineID() *string {
	if g == nil {
		return nil
	}
	return g.PipelineID
}

func (g *GetTelephonyResponse) GetType() *GetTelephonyResponseType {
	if g == nil {
		return nil
	}
	return g.Type
}

func (g *GetTelephonyResponse) GetAgentID() *string {
	if g == nil {
		return nil
	}
	return g.AgentID
}

func (g *GetTelephonyResponse) GetChannel() *string {
	if g == nil {
		return nil
	}
	return g.Channel
}

func (g *GetTelephonyResponse) GetReason() *GetTelephonyResponseReason {
	if g == nil {
		return nil
	}
	return g.Reason
}

func (g *GetTelephonyResponse) GetCreateTs() *int {
	if g == nil {
		return nil
	}
	return g.CreateTs
}

func (g *GetTelephonyResponse) GetState() *GetTelephonyResponseState {
	if g == nil {
		return nil
	}
	return g.State
}

func (g *GetTelephonyResponse) GetStopTs() *int {
	if g == nil {
		return nil
	}
	return g.StopTs
}

func (g *GetTelephonyResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetTelephonyResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetToNumber(toNumber *string) {
	g.ToNumber = toNumber
	g.require(getTelephonyResponseFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetFromNumber(fromNumber *string) {
	g.FromNumber = fromNumber
	g.require(getTelephonyResponseFieldFromNumber)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetPipelineID(pipelineID *string) {
	g.PipelineID = pipelineID
	g.require(getTelephonyResponseFieldPipelineID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetType(type_ *GetTelephonyResponseType) {
	g.Type = type_
	g.require(getTelephonyResponseFieldType)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetAgentID(agentID *string) {
	g.AgentID = agentID
	g.require(getTelephonyResponseFieldAgentID)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetChannel(channel *string) {
	g.Channel = channel
	g.require(getTelephonyResponseFieldChannel)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetReason(reason *GetTelephonyResponseReason) {
	g.Reason = reason
	g.require(getTelephonyResponseFieldReason)
}

// SetCreateTs sets the CreateTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetCreateTs(createTs *int) {
	g.CreateTs = createTs
	g.require(getTelephonyResponseFieldCreateTs)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetState(state *GetTelephonyResponseState) {
	g.State = state
	g.require(getTelephonyResponseFieldState)
}

// SetStopTs sets the StopTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTelephonyResponse) SetStopTs(stopTs *int) {
	g.StopTs = stopTs
	g.require(getTelephonyResponseFieldStopTs)
}

func (g *GetTelephonyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetTelephonyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetTelephonyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetTelephonyResponse) MarshalJSON() ([]byte, error) {
	type embed GetTelephonyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetTelephonyResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Reason for call ending:
// - `request`: Actively hung up.
// - `hangup`: The other party hung up.
// - `failed`: Call failed.
type GetTelephonyResponseReason string

const (
	GetTelephonyResponseReasonRequest GetTelephonyResponseReason = "request"
	GetTelephonyResponseReasonHangup  GetTelephonyResponseReason = "hangup"
	GetTelephonyResponseReasonFailed  GetTelephonyResponseReason = "failed"
)

func NewGetTelephonyResponseReasonFromString(s string) (GetTelephonyResponseReason, error) {
	switch s {
	case "request":
		return GetTelephonyResponseReasonRequest, nil
	case "hangup":
		return GetTelephonyResponseReasonHangup, nil
	case "failed":
		return GetTelephonyResponseReasonFailed, nil
	}
	var t GetTelephonyResponseReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetTelephonyResponseReason) Ptr() *GetTelephonyResponseReason {
	return &g
}

// Call status:
// - `answered`: The call was answered.
// - `hangup`: The call was disconnected.
type GetTelephonyResponseState string

const (
	GetTelephonyResponseStateAnswered GetTelephonyResponseState = "answered"
	GetTelephonyResponseStateHangup   GetTelephonyResponseState = "hangup"
)

func NewGetTelephonyResponseStateFromString(s string) (GetTelephonyResponseState, error) {
	switch s {
	case "answered":
		return GetTelephonyResponseStateAnswered, nil
	case "hangup":
		return GetTelephonyResponseStateHangup, nil
	}
	var t GetTelephonyResponseState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetTelephonyResponseState) Ptr() *GetTelephonyResponseState {
	return &g
}

// Call type:
// - `inbound`: Inbound call.
// - `outbound`: Outbound call.
type GetTelephonyResponseType string

const (
	GetTelephonyResponseTypeInbound  GetTelephonyResponseType = "inbound"
	GetTelephonyResponseTypeOutbound GetTelephonyResponseType = "outbound"
)

func NewGetTelephonyResponseTypeFromString(s string) (GetTelephonyResponseType, error) {
	switch s {
	case "inbound":
		return GetTelephonyResponseTypeInbound, nil
	case "outbound":
		return GetTelephonyResponseTypeOutbound, nil
	}
	var t GetTelephonyResponseType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetTelephonyResponseType) Ptr() *GetTelephonyResponseType {
	return &g
}

type HangupTelephonyResponse struct {

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (h *HangupTelephonyResponse) GetExtraProperties() map[string]interface{} {
	return h.extraProperties
}

func (h *HangupTelephonyResponse) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

func (h *HangupTelephonyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler HangupTelephonyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HangupTelephonyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties
	h.rawJSON = json.RawMessage(data)
	return nil
}

func (h *HangupTelephonyResponse) MarshalJSON() ([]byte, error) {
	type embed HangupTelephonyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*h),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, h.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (h *HangupTelephonyResponse) String() string {
	if len(h.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(h.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

type ListTelephonyRequestType string

const (
	ListTelephonyRequestTypeInbound  ListTelephonyRequestType = "inbound"
	ListTelephonyRequestTypeOutbound ListTelephonyRequestType = "outbound"
)

func NewListTelephonyRequestTypeFromString(s string) (ListTelephonyRequestType, error) {
	switch s {
	case "inbound":
		return ListTelephonyRequestTypeInbound, nil
	case "outbound":
		return ListTelephonyRequestTypeOutbound, nil
	}
	var t ListTelephonyRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListTelephonyRequestType) Ptr() *ListTelephonyRequestType {
	return &l
}

var (
	listTelephonyResponseFieldData   = big.NewInt(1 << 0)
	listTelephonyResponseFieldMeta   = big.NewInt(1 << 1)
	listTelephonyResponseFieldStatus = big.NewInt(1 << 2)
)

type ListTelephonyResponse struct {
	// Call data object.
	Data *ListTelephonyResponseData `json:"data" url:"data"`
	// Metadata about the list.
	Meta *ListTelephonyResponseMeta `json:"meta,omitempty" url:"meta,omitempty"`
	// Request status.
	Status *string `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListTelephonyResponse) GetData() *ListTelephonyResponseData {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListTelephonyResponse) GetMeta() *ListTelephonyResponseMeta {
	if l == nil {
		return nil
	}
	return l.Meta
}

func (l *ListTelephonyResponse) GetStatus() *string {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListTelephonyResponse) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListTelephonyResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponse) SetData(data *ListTelephonyResponseData) {
	l.Data = data
	l.require(listTelephonyResponseFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponse) SetMeta(meta *ListTelephonyResponseMeta) {
	l.Meta = meta
	l.require(listTelephonyResponseFieldMeta)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponse) SetStatus(status *string) {
	l.Status = status
	l.require(listTelephonyResponseFieldStatus)
}

func (l *ListTelephonyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListTelephonyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListTelephonyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListTelephonyResponse) MarshalJSON() ([]byte, error) {
	type embed ListTelephonyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListTelephonyResponse) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Call data object.
var (
	listTelephonyResponseDataFieldCount = big.NewInt(1 << 0)
	listTelephonyResponseDataFieldList  = big.NewInt(1 << 1)
)

type ListTelephonyResponseData struct {
	// The number of calls returned in this response.
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// A list of calls that meet the criteria.
	List []*ListTelephonyResponseDataListItem `json:"list" url:"list"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListTelephonyResponseData) GetCount() *int {
	if l == nil {
		return nil
	}
	return l.Count
}

func (l *ListTelephonyResponseData) GetList() []*ListTelephonyResponseDataListItem {
	if l == nil {
		return nil
	}
	return l.List
}

func (l *ListTelephonyResponseData) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListTelephonyResponseData) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseData) SetCount(count *int) {
	l.Count = count
	l.require(listTelephonyResponseDataFieldCount)
}

// SetList sets the List field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseData) SetList(list []*ListTelephonyResponseDataListItem) {
	l.List = list
	l.require(listTelephonyResponseDataFieldList)
}

func (l *ListTelephonyResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler ListTelephonyResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListTelephonyResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListTelephonyResponseData) MarshalJSON() ([]byte, error) {
	type embed ListTelephonyResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListTelephonyResponseData) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listTelephonyResponseDataListItemFieldToNumber   = big.NewInt(1 << 0)
	listTelephonyResponseDataListItemFieldFromNumber = big.NewInt(1 << 1)
	listTelephonyResponseDataListItemFieldPipelineID = big.NewInt(1 << 2)
	listTelephonyResponseDataListItemFieldType       = big.NewInt(1 << 3)
	listTelephonyResponseDataListItemFieldAgentID    = big.NewInt(1 << 4)
	listTelephonyResponseDataListItemFieldChannel    = big.NewInt(1 << 5)
	listTelephonyResponseDataListItemFieldCreateTs   = big.NewInt(1 << 6)
	listTelephonyResponseDataListItemFieldState      = big.NewInt(1 << 7)
	listTelephonyResponseDataListItemFieldStopTs     = big.NewInt(1 << 8)
)

type ListTelephonyResponseDataListItem struct {
	// The number called.
	ToNumber *string `json:"to_number,omitempty" url:"to_number,omitempty"`
	// Caller ID.
	FromNumber *string `json:"from_number,omitempty" url:"from_number,omitempty"`
	// The unique ID of a published project in AI Studio. Can be obtained in AI Studio - Project - Release Management.
	PipelineID *string `json:"pipeline_id,omitempty" url:"pipeline_id,omitempty"`
	// Call type:
	// - `inbound`: Inbound call.
	// - `outbound`: Outbound call.
	Type *ListTelephonyResponseDataListItemType `json:"type,omitempty" url:"type,omitempty"`
	// A unique identifier for the call session.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	// RTC channel name.
	Channel *string `json:"channel,omitempty" url:"channel,omitempty"`
	// Call creation timestamp (in seconds).
	CreateTs *int `json:"create_ts,omitempty" url:"create_ts,omitempty"`
	// Call status:
	// - `answered`: The call was answered.
	// - `hangup`: The call was disconnected.
	State *ListTelephonyResponseDataListItemState `json:"state,omitempty" url:"state,omitempty"`
	// Call end timestamp (in seconds). Returns `0` or `null` if the call has not ended.
	StopTs *int `json:"stop_ts,omitempty" url:"stop_ts,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListTelephonyResponseDataListItem) GetToNumber() *string {
	if l == nil {
		return nil
	}
	return l.ToNumber
}

func (l *ListTelephonyResponseDataListItem) GetFromNumber() *string {
	if l == nil {
		return nil
	}
	return l.FromNumber
}

func (l *ListTelephonyResponseDataListItem) GetPipelineID() *string {
	if l == nil {
		return nil
	}
	return l.PipelineID
}

func (l *ListTelephonyResponseDataListItem) GetType() *ListTelephonyResponseDataListItemType {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *ListTelephonyResponseDataListItem) GetAgentID() *string {
	if l == nil {
		return nil
	}
	return l.AgentID
}

func (l *ListTelephonyResponseDataListItem) GetChannel() *string {
	if l == nil {
		return nil
	}
	return l.Channel
}

func (l *ListTelephonyResponseDataListItem) GetCreateTs() *int {
	if l == nil {
		return nil
	}
	return l.CreateTs
}

func (l *ListTelephonyResponseDataListItem) GetState() *ListTelephonyResponseDataListItemState {
	if l == nil {
		return nil
	}
	return l.State
}

func (l *ListTelephonyResponseDataListItem) GetStopTs() *int {
	if l == nil {
		return nil
	}
	return l.StopTs
}

func (l *ListTelephonyResponseDataListItem) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListTelephonyResponseDataListItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetToNumber sets the ToNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetToNumber(toNumber *string) {
	l.ToNumber = toNumber
	l.require(listTelephonyResponseDataListItemFieldToNumber)
}

// SetFromNumber sets the FromNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetFromNumber(fromNumber *string) {
	l.FromNumber = fromNumber
	l.require(listTelephonyResponseDataListItemFieldFromNumber)
}

// SetPipelineID sets the PipelineID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetPipelineID(pipelineID *string) {
	l.PipelineID = pipelineID
	l.require(listTelephonyResponseDataListItemFieldPipelineID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetType(type_ *ListTelephonyResponseDataListItemType) {
	l.Type = type_
	l.require(listTelephonyResponseDataListItemFieldType)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetAgentID(agentID *string) {
	l.AgentID = agentID
	l.require(listTelephonyResponseDataListItemFieldAgentID)
}

// SetChannel sets the Channel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetChannel(channel *string) {
	l.Channel = channel
	l.require(listTelephonyResponseDataListItemFieldChannel)
}

// SetCreateTs sets the CreateTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetCreateTs(createTs *int) {
	l.CreateTs = createTs
	l.require(listTelephonyResponseDataListItemFieldCreateTs)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetState(state *ListTelephonyResponseDataListItemState) {
	l.State = state
	l.require(listTelephonyResponseDataListItemFieldState)
}

// SetStopTs sets the StopTs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseDataListItem) SetStopTs(stopTs *int) {
	l.StopTs = stopTs
	l.require(listTelephonyResponseDataListItemFieldStopTs)
}

func (l *ListTelephonyResponseDataListItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListTelephonyResponseDataListItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListTelephonyResponseDataListItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListTelephonyResponseDataListItem) MarshalJSON() ([]byte, error) {
	type embed ListTelephonyResponseDataListItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListTelephonyResponseDataListItem) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Call status:
// - `answered`: The call was answered.
// - `hangup`: The call was disconnected.
type ListTelephonyResponseDataListItemState string

const (
	ListTelephonyResponseDataListItemStateAnswered ListTelephonyResponseDataListItemState = "answered"
	ListTelephonyResponseDataListItemStateHangup   ListTelephonyResponseDataListItemState = "hangup"
)

func NewListTelephonyResponseDataListItemStateFromString(s string) (ListTelephonyResponseDataListItemState, error) {
	switch s {
	case "answered":
		return ListTelephonyResponseDataListItemStateAnswered, nil
	case "hangup":
		return ListTelephonyResponseDataListItemStateHangup, nil
	}
	var t ListTelephonyResponseDataListItemState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListTelephonyResponseDataListItemState) Ptr() *ListTelephonyResponseDataListItemState {
	return &l
}

// Call type:
// - `inbound`: Inbound call.
// - `outbound`: Outbound call.
type ListTelephonyResponseDataListItemType string

const (
	ListTelephonyResponseDataListItemTypeInbound  ListTelephonyResponseDataListItemType = "inbound"
	ListTelephonyResponseDataListItemTypeOutbound ListTelephonyResponseDataListItemType = "outbound"
)

func NewListTelephonyResponseDataListItemTypeFromString(s string) (ListTelephonyResponseDataListItemType, error) {
	switch s {
	case "inbound":
		return ListTelephonyResponseDataListItemTypeInbound, nil
	case "outbound":
		return ListTelephonyResponseDataListItemTypeOutbound, nil
	}
	var t ListTelephonyResponseDataListItemType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListTelephonyResponseDataListItemType) Ptr() *ListTelephonyResponseDataListItemType {
	return &l
}

// Metadata about the list.
var (
	listTelephonyResponseMetaFieldCursor = big.NewInt(1 << 0)
	listTelephonyResponseMetaFieldTotal  = big.NewInt(1 << 1)
)

type ListTelephonyResponseMeta struct {
	// Pagination cursor for the next page.
	Cursor *string `json:"cursor,omitempty" url:"cursor,omitempty"`
	// The total number of calls that meet the query criteria.
	Total *int `json:"total,omitempty" url:"total,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListTelephonyResponseMeta) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListTelephonyResponseMeta) GetTotal() *int {
	if l == nil {
		return nil
	}
	return l.Total
}

func (l *ListTelephonyResponseMeta) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *ListTelephonyResponseMeta) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseMeta) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listTelephonyResponseMetaFieldCursor)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTelephonyResponseMeta) SetTotal(total *int) {
	l.Total = total
	l.require(listTelephonyResponseMetaFieldTotal)
}

func (l *ListTelephonyResponseMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler ListTelephonyResponseMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListTelephonyResponseMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListTelephonyResponseMeta) MarshalJSON() ([]byte, error) {
	type embed ListTelephonyResponseMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListTelephonyResponseMeta) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
