// Code generated by Fern. DO NOT EDIT.

package Agora

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/AgoraIO/agora-agents-go/internal"
	big "math/big"
)

// Error response returned when a Conversational AI Agent Management API request fails.
//
// Common HTTP status codes include:
// - `400`: Invalid request parameters.
// - `401`: Authentication failed.
// - `403`: Unauthorized access or service not enabled.
// - `404`: Agent not found or has exited.
// - `409`: Agent conflict.
// - `422`: Access limit exceeded.
// - `429`: Request rate limit exceeded.
// - `500`: Internal server error.
// - `502`: Gateway error.
// - `503`: Agent startup failure.
// - `504`: Request timeout.
var (
	agentErrorResponseFieldDetail = big.NewInt(1 << 0)
	agentErrorResponseFieldReason = big.NewInt(1 << 1)
)

type AgentErrorResponse struct {
	// Error detail message.
	Detail *string `json:"detail,omitempty" url:"detail,omitempty"`
	// Error reason code.
	Reason *AgentErrorResponseReason `json:"reason,omitempty" url:"reason,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentErrorResponse) GetDetail() *string {
	if a == nil {
		return nil
	}
	return a.Detail
}

func (a *AgentErrorResponse) GetReason() *AgentErrorResponseReason {
	if a == nil {
		return nil
	}
	return a.Reason
}

func (a *AgentErrorResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AgentErrorResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetDetail sets the Detail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentErrorResponse) SetDetail(detail *string) {
	a.Detail = detail
	a.require(agentErrorResponseFieldDetail)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentErrorResponse) SetReason(reason *AgentErrorResponseReason) {
	a.Reason = reason
	a.require(agentErrorResponseFieldReason)
}

func (a *AgentErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentErrorResponse) MarshalJSON() ([]byte, error) {
	type embed AgentErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentErrorResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Error reason code.
type AgentErrorResponseReason string

const (
	AgentErrorResponseReasonServiceNotEnabled          AgentErrorResponseReason = "ServiceNotEnabled"
	AgentErrorResponseReasonAccountSuspended           AgentErrorResponseReason = "AccountSuspended"
	AgentErrorResponseReasonInternalError              AgentErrorResponseReason = "InternalError"
	AgentErrorResponseReasonInvalidPermission          AgentErrorResponseReason = "InvalidPermission"
	AgentErrorResponseReasonInvalidRequestBody         AgentErrorResponseReason = "InvalidRequestBody"
	AgentErrorResponseReasonMissingRequiredField       AgentErrorResponseReason = "MissingRequiredField"
	AgentErrorResponseReasonInvalidFieldValue          AgentErrorResponseReason = "InvalidFieldValue"
	AgentErrorResponseReasonResourceQuotaLimitExceeded AgentErrorResponseReason = "ResourceQuotaLimitExceeded"
	AgentErrorResponseReasonConcurrencyLimitExceeded   AgentErrorResponseReason = "ConcurrencyLimitExceeded"
	AgentErrorResponseReasonServiceUnavailable         AgentErrorResponseReason = "ServiceUnavailable"
	AgentErrorResponseReasonResourceAllocationFailed   AgentErrorResponseReason = "ResourceAllocationFailed"
	AgentErrorResponseReasonTaskConflict               AgentErrorResponseReason = "TaskConflict"
	AgentErrorResponseReasonTaskNotFound               AgentErrorResponseReason = "TaskNotFound"
	AgentErrorResponseReasonTaskOperationTimeout       AgentErrorResponseReason = "TaskOperationTimeout"
	AgentErrorResponseReasonNotImplemented             AgentErrorResponseReason = "NotImplemented"
)

func NewAgentErrorResponseReasonFromString(s string) (AgentErrorResponseReason, error) {
	switch s {
	case "ServiceNotEnabled":
		return AgentErrorResponseReasonServiceNotEnabled, nil
	case "AccountSuspended":
		return AgentErrorResponseReasonAccountSuspended, nil
	case "InternalError":
		return AgentErrorResponseReasonInternalError, nil
	case "InvalidPermission":
		return AgentErrorResponseReasonInvalidPermission, nil
	case "InvalidRequestBody":
		return AgentErrorResponseReasonInvalidRequestBody, nil
	case "MissingRequiredField":
		return AgentErrorResponseReasonMissingRequiredField, nil
	case "InvalidFieldValue":
		return AgentErrorResponseReasonInvalidFieldValue, nil
	case "ResourceQuotaLimitExceeded":
		return AgentErrorResponseReasonResourceQuotaLimitExceeded, nil
	case "ConcurrencyLimitExceeded":
		return AgentErrorResponseReasonConcurrencyLimitExceeded, nil
	case "ServiceUnavailable":
		return AgentErrorResponseReasonServiceUnavailable, nil
	case "ResourceAllocationFailed":
		return AgentErrorResponseReasonResourceAllocationFailed, nil
	case "TaskConflict":
		return AgentErrorResponseReasonTaskConflict, nil
	case "TaskNotFound":
		return AgentErrorResponseReasonTaskNotFound, nil
	case "TaskOperationTimeout":
		return AgentErrorResponseReasonTaskOperationTimeout, nil
	case "NotImplemented":
		return AgentErrorResponseReasonNotImplemented, nil
	}
	var t AgentErrorResponseReason
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentErrorResponseReason) Ptr() *AgentErrorResponseReason {
	return &a
}

// Error response returned when a Telephony or Phone Number Management API request fails.
//
// The response body includes `error_type` and `description` fields (not the Agent Management `detail`/`reason` shape).
var (
	telephonyErrorResponseFieldErrorType   = big.NewInt(1 << 0)
	telephonyErrorResponseFieldDescription = big.NewInt(1 << 1)
)

type TelephonyErrorResponse struct {
	// The type of error that occurred.
	ErrorType *string `json:"error_type,omitempty" url:"error_type,omitempty"`
	// A detailed description of the error.
	Description *string `json:"description,omitempty" url:"description,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TelephonyErrorResponse) GetErrorType() *string {
	if t == nil {
		return nil
	}
	return t.ErrorType
}

func (t *TelephonyErrorResponse) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TelephonyErrorResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TelephonyErrorResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetErrorType sets the ErrorType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyErrorResponse) SetErrorType(errorType *string) {
	t.ErrorType = errorType
	t.require(telephonyErrorResponseFieldErrorType)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TelephonyErrorResponse) SetDescription(description *string) {
	t.Description = description
	t.require(telephonyErrorResponseFieldDescription)
}

func (t *TelephonyErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TelephonyErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TelephonyErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TelephonyErrorResponse) MarshalJSON() ([]byte, error) {
	type embed TelephonyErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TelephonyErrorResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
