// Code generated by Fern. DO NOT EDIT.

package agentmanagement

import (
	context "context"
	Agora "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go"
	core "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/core"
	internal "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/internal"
	option "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Send a custom text instruction to the specified conversational AI agent instance.
//
// The instruction is injected into the current conversation pipeline as user input, and the agent processes and responds to it following the standard user input logic.
//
// Use this endpoint for the following scenarios:
// - **Implicit instruction injection**: Inject hidden context or directives into the conversation.
// - **Client-side event triggering**: Notify the agent of client-side events, such as a user clicking a button.
// - **Voice and text collaboration**: Combine text instructions with voice input for richer interaction.
func (c *Client) AgentThink(
	ctx context.Context,
	request *Agora.AgentThinkAgentManagementRequest,
	opts ...option.RequestOption,
) (*Agora.AgentThinkAgentManagementResponse, error) {
	response, err := c.WithRawResponse.AgentThink(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
