// Code generated by Fern. DO NOT EDIT.

package agentmanagement

import (
	context "context"
	Agora "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go"
	core "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/core"
	internal "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/internal"
	option "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) AgentThink(
	ctx context.Context,
	request *Agora.AgentThinkAgentManagementRequest,
	opts ...option.RequestOption,
) (*core.Response[*Agora.AgentThinkAgentManagementResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.agora.io/api/conversational-ai-agent",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/projects/%v/agents/%v/think",
		request.Appid,
		request.AgentID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *Agora.AgentThinkAgentManagementResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*Agora.AgentThinkAgentManagementResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
