// Code generated by Fern. DO NOT EDIT.

package telephony_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	Agora "github.com/AgoraIO/agora-agents-go/v2"
	client "github.com/AgoraIO/agora-agents-go/v2/client"
	option "github.com/AgoraIO/agora-agents-go/v2/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestTelephonyListWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.ListTelephonyRequest{
		Appid: "appid",
	}
	_, invocationErr := client.Telephony.List(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/projects/appid/call", nil, 1)
}

func TestTelephonyCallWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.CallTelephonyRequest{
		Appid: "appid",
		Name:  "customer_service",
		Sip: &Agora.CallTelephonyRequestSip{
			ToNumber:   "+19876543210",
			FromNumber: "+11234567890",
			RtcUID:     "100",
			RtcToken:   "<agora_sip_rtc_token>",
		},
		PipelineID: Agora.String(
			"fzufjlweixxxxnlp",
		),
		Properties: &Agora.CallTelephonyRequestProperties{
			Channel:     "<agora_channel>",
			Token:       "<agora_channel_token>",
			AgentRtcUID: "111",
			RemoteRtcUIDs: []string{
				"100",
			},
		},
	}
	_, invocationErr := client.Telephony.Call(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/projects/appid/call", nil, 1)
}

func TestTelephonyGetWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.GetTelephonyRequest{
		Appid:   "appid",
		AgentID: "agent_id",
	}
	_, invocationErr := client.Telephony.Get(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/projects/appid/calls/agent_id", nil, 1)
}

func TestTelephonyHangupWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.HangupTelephonyRequest{
		Appid:   "appid",
		AgentID: "agent_id",
	}
	_, invocationErr := client.Telephony.Hangup(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/projects/appid/calls/agent_id/hangup", nil, 1)
}
