// Code generated by Fern. DO NOT EDIT.

package phone_numbers_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	Agora "github.com/AgoraIO/agora-agents-go"
	client "github.com/AgoraIO/agora-agents-go/client"
	option "github.com/AgoraIO/agora-agents-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPhoneNumbersListWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.PhoneNumbers.List(
		context.TODO(),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/phone-numbers", nil, 1)
}

func TestPhoneNumbersAddWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.AddPhoneNumbersRequest{
		Provider:    Agora.AddPhoneNumbersRequestProviderByo,
		PhoneNumber: "+19876543210",
		Label:       "Sales Hotline",
		Inbound: Agora.Bool(
			true,
		),
		Outbound: Agora.Bool(
			true,
		),
		InboundConfig: &Agora.AddPhoneNumbersRequestInboundConfig{
			AllowedAddresses: []string{
				"112.126.15.64/27",
			},
		},
		OutboundConfig: &Agora.AddPhoneNumbersRequestOutboundConfig{
			Address: Agora.String(
				"xxx:xxx@sip.example.com",
			),
			Transport: Agora.String(
				"tls",
			),
		},
	}
	_, invocationErr := client.PhoneNumbers.Add(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/phone-numbers", nil, 1)
}

func TestPhoneNumbersGetWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.GetPhoneNumbersRequest{
		PhoneNumber: "phone_number",
	}
	_, invocationErr := client.PhoneNumbers.Get(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/v2/phone-numbers/phone_number", nil, 1)
}

func TestPhoneNumbersDeleteWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.DeletePhoneNumbersRequest{
		PhoneNumber: "phone_number",
	}
	invocationErr := client.PhoneNumbers.Delete(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "DELETE", "/v2/phone-numbers/phone_number", nil, 1)
}

func TestPhoneNumbersUpdateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.UpdatePhoneNumbersRequest{
		PhoneNumber: "phone_number",
		InboundConfig: &Agora.UpdatePhoneNumbersRequestInboundConfig{
			PipelineID: Agora.String(
				"xxxxx",
			),
		},
		OutboundConfig: &Agora.UpdatePhoneNumbersRequestOutboundConfig{
			PipelineID: Agora.String(
				"xxxxx",
			),
		},
	}
	_, invocationErr := client.PhoneNumbers.Update(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PATCH", "/v2/phone-numbers/phone_number", nil, 1)
}
