// Code generated by Fern. DO NOT EDIT.

package phonenumbers

import (
	context "context"
	Agora "github.com/AgoraIO/agora-agents-go"
	core "github.com/AgoraIO/agora-agents-go/core"
	internal "github.com/AgoraIO/agora-agents-go/internal"
	option "github.com/AgoraIO/agora-agents-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve a list of all imported phone numbers under the current account.
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*Agora.ListPhoneNumbersResponseItem, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Import a pre-configured phone number that can be used for inbound or outbound calls.
func (c *Client) Add(
	ctx context.Context,
	request *Agora.AddPhoneNumbersRequest,
	opts ...option.RequestOption,
) (*Agora.AddPhoneNumbersResponse, error) {
	response, err := c.WithRawResponse.Add(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve detailed information for a specific phone number.
func (c *Client) Get(
	ctx context.Context,
	request *Agora.GetPhoneNumbersRequest,
	opts ...option.RequestOption,
) (*Agora.GetPhoneNumbersResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Remove an imported phone number from the system.
//
// After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.
// > This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted.
func (c *Client) Delete(
	ctx context.Context,
	request *Agora.DeletePhoneNumbersRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Update the configuration for a phone number.
func (c *Client) Update(
	ctx context.Context,
	request *Agora.UpdatePhoneNumbersRequest,
	opts ...option.RequestOption,
) (*Agora.UpdatePhoneNumbersResponse, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
