// Code generated by Fern. DO NOT EDIT.

package agent_management_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	Agora "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go"
	client "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/client"
	option "github.com/AgoraIO-Conversational-AI/agent-server-sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAgentManagementAgentThinkWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &Agora.AgentThinkAgentManagementRequest{
		Appid:             "appid",
		AgentID:           "agentId",
		Text:              "The user just clicked the purchase button.",
		OnListeningAction: Agora.AgentThinkAgentManagementRequestOnListeningActionInject.Ptr(),
		OnThinkingAction:  Agora.AgentThinkAgentManagementRequestOnThinkingActionInterrupt.Ptr(),
		OnSpeakingAction:  Agora.AgentThinkAgentManagementRequestOnSpeakingActionIgnore.Ptr(),
		Interruptable: Agora.Bool(
			true,
		),
		Metadata: map[string]string{
			"publisher": "user123",
			"model":     "deepseek-r1",
		},
	}
	_, invocationErr := client.AgentManagement.AgentThink(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/projects/appid/agents/agentId/think", nil, 1)
}
